# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainWindowUI.ui'
#
# Created by: PyQt5 UI code generator 5.5
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1000, 700)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(1000, 700))
        MainWindow.setMaximumSize(QtCore.QSize(1000, 700))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("Zrzuty/PP_logo_jasne.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setObjectName("label")
        self.verticalLayout_3.addWidget(self.label)
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        self.tabWidget.setMinimumSize(QtCore.QSize(150, 180))
        self.tabWidget.setMaximumSize(QtCore.QSize(150, 180))
        self.tabWidget.setObjectName("tabWidget")
        self.uart = QtWidgets.QWidget()
        self.uart.setObjectName("uart")
        self.label_2 = QtWidgets.QLabel(self.uart)
        self.label_2.setGeometry(QtCore.QRect(10, 10, 55, 16))
        self.label_2.setObjectName("label_2")
        self.uartPortList = QtWidgets.QComboBox(self.uart)
        self.uartPortList.setGeometry(QtCore.QRect(10, 30, 111, 22))
        self.uartPortList.setObjectName("uartPortList")
        self.label_3 = QtWidgets.QLabel(self.uart)
        self.label_3.setGeometry(QtCore.QRect(10, 90, 71, 16))
        self.label_3.setObjectName("label_3")
        self.uartBaudRateList = QtWidgets.QComboBox(self.uart)
        self.uartBaudRateList.setGeometry(QtCore.QRect(10, 110, 111, 22))
        self.uartBaudRateList.setObjectName("uartBaudRateList")
        self.uartBaudRateList.addItem("")
        self.uartBaudRateList.addItem("")
        self.uartBaudRateList.addItem("")
        self.uartBaudRateList.addItem("")
        self.uartBaudRateList.addItem("")
        self.uartBaudRateList.addItem("")
        self.uartBaudRateList.addItem("")
        self.uartBaudRateList.addItem("")
        self.uartBaudRateList.addItem("")
        self.uartBaudRateList.addItem("")
        self.uartBaudRateList.addItem("")
        self.uartBaudRateList.addItem("")
        self.uartBaudRateList.addItem("")
        self.uartBaudRateList.addItem("")
        self.rescanButton = QtWidgets.QPushButton(self.uart)
        self.rescanButton.setGeometry(QtCore.QRect(10, 60, 93, 28))
        self.rescanButton.setObjectName("rescanButton")
        self.tabWidget.addTab(self.uart, "")
        self.usb_hid = QtWidgets.QWidget()
        self.usb_hid.setObjectName("usb_hid")
        self.label_4 = QtWidgets.QLabel(self.usb_hid)
        self.label_4.setGeometry(QtCore.QRect(10, 10, 71, 16))
        self.label_4.setObjectName("label_4")
        self.vendorID = QtWidgets.QLineEdit(self.usb_hid)
        self.vendorID.setGeometry(QtCore.QRect(10, 30, 113, 22))
        self.vendorID.setObjectName("vendorID")
        self.label_5 = QtWidgets.QLabel(self.usb_hid)
        self.label_5.setGeometry(QtCore.QRect(10, 90, 71, 16))
        self.label_5.setObjectName("label_5")
        self.productID = QtWidgets.QLineEdit(self.usb_hid)
        self.productID.setGeometry(QtCore.QRect(10, 110, 113, 22))
        self.productID.setObjectName("productID")
        self.tabWidget.addTab(self.usb_hid, "")
        self.verticalLayout_3.addWidget(self.tabWidget)
        self.connectButton = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.connectButton.sizePolicy().hasHeightForWidth())
        self.connectButton.setSizePolicy(sizePolicy)
        self.connectButton.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.connectButton.setObjectName("connectButton")
        self.verticalLayout_3.addWidget(self.connectButton)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem)
        self.horizontalLayout.addLayout(self.verticalLayout_3)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.groupBox_4 = QtWidgets.QGroupBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_4.sizePolicy().hasHeightForWidth())
        self.groupBox_4.setSizePolicy(sizePolicy)
        self.groupBox_4.setMinimumSize(QtCore.QSize(0, 60))
        self.groupBox_4.setObjectName("groupBox_4")
        self.label_14 = QtWidgets.QLabel(self.groupBox_4)
        self.label_14.setGeometry(QtCore.QRect(5, 80, 151, 16))
        self.label_14.setObjectName("label_14")
        self.speedMeterN1 = QtWidgets.QLabel(self.groupBox_4)
        self.speedMeterN1.setGeometry(QtCore.QRect(134, 80, 71, 20))
        self.speedMeterN1.setObjectName("speedMeterN1")
        self.label_15 = QtWidgets.QLabel(self.groupBox_4)
        self.label_15.setGeometry(QtCore.QRect(5, 200, 81, 16))
        self.label_15.setObjectName("label_15")
        self.voltageMeter = QtWidgets.QLabel(self.groupBox_4)
        self.voltageMeter.setGeometry(QtCore.QRect(134, 200, 71, 20))
        self.voltageMeter.setObjectName("voltageMeter")
        self.label_16 = QtWidgets.QLabel(self.groupBox_4)
        self.label_16.setGeometry(QtCore.QRect(5, 140, 71, 16))
        self.label_16.setObjectName("label_16")
        self.currentMeterI1 = QtWidgets.QLabel(self.groupBox_4)
        self.currentMeterI1.setGeometry(QtCore.QRect(134, 140, 71, 20))
        self.currentMeterI1.setObjectName("currentMeterI1")
        self.label_17 = QtWidgets.QLabel(self.groupBox_4)
        self.label_17.setGeometry(QtCore.QRect(5, 230, 71, 16))
        self.label_17.setObjectName("label_17")
        self.pressureMeter = QtWidgets.QLabel(self.groupBox_4)
        self.pressureMeter.setGeometry(QtCore.QRect(134, 230, 71, 20))
        self.pressureMeter.setObjectName("pressureMeter")
        self.label_18 = QtWidgets.QLabel(self.groupBox_4)
        self.label_18.setGeometry(QtCore.QRect(5, 170, 71, 20))
        self.label_18.setObjectName("label_18")
        self.currentMeterI2 = QtWidgets.QLabel(self.groupBox_4)
        self.currentMeterI2.setGeometry(QtCore.QRect(134, 170, 71, 20))
        self.currentMeterI2.setObjectName("currentMeterI2")
        self.label_19 = QtWidgets.QLabel(self.groupBox_4)
        self.label_19.setGeometry(QtCore.QRect(5, 110, 151, 16))
        self.label_19.setObjectName("label_19")
        self.speedMeterN2 = QtWidgets.QLabel(self.groupBox_4)
        self.speedMeterN2.setGeometry(QtCore.QRect(134, 110, 71, 20))
        self.speedMeterN2.setObjectName("speedMeterN2")
        self.label_20 = QtWidgets.QLabel(self.groupBox_4)
        self.label_20.setGeometry(QtCore.QRect(5, 20, 71, 16))
        self.label_20.setObjectName("label_20")
        self.PWMFirstMeter = QtWidgets.QLabel(self.groupBox_4)
        self.PWMFirstMeter.setGeometry(QtCore.QRect(134, 20, 71, 20))
        self.PWMFirstMeter.setObjectName("PWMFirstMeter")
        self.label_24 = QtWidgets.QLabel(self.groupBox_4)
        self.label_24.setGeometry(QtCore.QRect(5, 50, 81, 16))
        self.label_24.setObjectName("label_24")
        self.PWMSecondMeter = QtWidgets.QLabel(self.groupBox_4)
        self.PWMSecondMeter.setGeometry(QtCore.QRect(134, 50, 71, 20))
        self.PWMSecondMeter.setObjectName("PWMSecondMeter")
        self.line = QtWidgets.QFrame(self.groupBox_4)
        self.line.setGeometry(QtCore.QRect(0, 215, 207, 16))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.line_2 = QtWidgets.QFrame(self.groupBox_4)
        self.line_2.setGeometry(QtCore.QRect(0, 185, 207, 16))
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.line_3 = QtWidgets.QFrame(self.groupBox_4)
        self.line_3.setGeometry(QtCore.QRect(0, 155, 207, 16))
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.line_4 = QtWidgets.QFrame(self.groupBox_4)
        self.line_4.setGeometry(QtCore.QRect(0, 125, 207, 16))
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.line_5 = QtWidgets.QFrame(self.groupBox_4)
        self.line_5.setGeometry(QtCore.QRect(0, 95, 207, 16))
        self.line_5.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.line_6 = QtWidgets.QFrame(self.groupBox_4)
        self.line_6.setGeometry(QtCore.QRect(0, 65, 207, 16))
        self.line_6.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_6.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_6.setObjectName("line_6")
        self.line_7 = QtWidgets.QFrame(self.groupBox_4)
        self.line_7.setGeometry(QtCore.QRect(0, 35, 207, 16))
        self.line_7.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_7.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_7.setObjectName("line_7")
        self.horizontalLayout_2.addWidget(self.groupBox_4)
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_2.sizePolicy().hasHeightForWidth())
        self.groupBox_2.setSizePolicy(sizePolicy)
        self.groupBox_2.setObjectName("groupBox_2")
        self.label_6 = QtWidgets.QLabel(self.groupBox_2)
        self.label_6.setGeometry(QtCore.QRect(10, 20, 161, 31))
        self.label_6.setWordWrap(True)
        self.label_6.setObjectName("label_6")
        self.calibrateTens = QtWidgets.QPushButton(self.groupBox_2)
        self.calibrateTens.setGeometry(QtCore.QRect(10, 220, 93, 28))
        self.calibrateTens.setObjectName("calibrateTens")
        self.label_13 = QtWidgets.QLabel(self.groupBox_2)
        self.label_13.setGeometry(QtCore.QRect(10, 200, 81, 16))
        self.label_13.setObjectName("label_13")
        self.poleNumber = QtWidgets.QSpinBox(self.groupBox_2)
        self.poleNumber.setGeometry(QtCore.QRect(10, 60, 81, 22))
        self.poleNumber.setMaximum(127)
        self.poleNumber.setObjectName("poleNumber")
        self.label_21 = QtWidgets.QLabel(self.groupBox_2)
        self.label_21.setGeometry(QtCore.QRect(10, 80, 171, 41))
        self.label_21.setWordWrap(True)
        self.label_21.setObjectName("label_21")
        self.poleNumberTwo = QtWidgets.QSpinBox(self.groupBox_2)
        self.poleNumberTwo.setGeometry(QtCore.QRect(10, 120, 81, 22))
        self.poleNumberTwo.setMaximum(127)
        self.poleNumberTwo.setObjectName("poleNumberTwo")
        self.manualTime = QtWidgets.QLabel(self.groupBox_2)
        self.manualTime.setGeometry(QtCore.QRect(10, 150, 181, 16))
        self.manualTime.setObjectName("manualTime")
        self.safetyTime = QtWidgets.QSpinBox(self.groupBox_2)
        self.safetyTime.setGeometry(QtCore.QRect(10, 170, 81, 22))
        self.safetyTime.setMinimum(1)
        self.safetyTime.setMaximum(127)
        self.safetyTime.setProperty("value", 10)
        self.safetyTime.setObjectName("safetyTime")
        self.horizontalLayout_2.addWidget(self.groupBox_2)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.manualWork = QtWidgets.QCheckBox(self.centralwidget)
        self.manualWork.setObjectName("manualWork")
        self.verticalLayout_5.addWidget(self.manualWork)
        self.manualGroupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.manualGroupBox.setObjectName("manualGroupBox")
        self.label_7 = QtWidgets.QLabel(self.manualGroupBox)
        self.label_7.setGeometry(QtCore.QRect(10, 20, 101, 16))
        self.label_7.setObjectName("label_7")
        self.engOneMin = QtWidgets.QPushButton(self.manualGroupBox)
        self.engOneMin.setGeometry(QtCore.QRect(10, 40, 35, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.engOneMin.setFont(font)
        self.engOneMin.setObjectName("engOneMin")
        self.engOnePlus = QtWidgets.QPushButton(self.manualGroupBox)
        self.engOnePlus.setGeometry(QtCore.QRect(70, 40, 35, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.engOnePlus.setFont(font)
        self.engOnePlus.setObjectName("engOnePlus")
        self.engTwoPlus = QtWidgets.QPushButton(self.manualGroupBox)
        self.engTwoPlus.setGeometry(QtCore.QRect(70, 90, 35, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.engTwoPlus.setFont(font)
        self.engTwoPlus.setObjectName("engTwoPlus")
        self.engTwoMin = QtWidgets.QPushButton(self.manualGroupBox)
        self.engTwoMin.setGeometry(QtCore.QRect(10, 90, 35, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.engTwoMin.setFont(font)
        self.engTwoMin.setObjectName("engTwoMin")
        self.label_9 = QtWidgets.QLabel(self.manualGroupBox)
        self.label_9.setGeometry(QtCore.QRect(10, 70, 101, 16))
        self.label_9.setObjectName("label_9")
        self.engBothPlus = QtWidgets.QPushButton(self.manualGroupBox)
        self.engBothPlus.setGeometry(QtCore.QRect(70, 140, 35, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.engBothPlus.setFont(font)
        self.engBothPlus.setObjectName("engBothPlus")
        self.engBothMin = QtWidgets.QPushButton(self.manualGroupBox)
        self.engBothMin.setGeometry(QtCore.QRect(10, 140, 35, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.engBothMin.setFont(font)
        self.engBothMin.setObjectName("engBothMin")
        self.label_10 = QtWidgets.QLabel(self.manualGroupBox)
        self.label_10.setGeometry(QtCore.QRect(10, 120, 101, 16))
        self.label_10.setObjectName("label_10")
        self.engOneJump = QtWidgets.QSpinBox(self.manualGroupBox)
        self.engOneJump.setGeometry(QtCore.QRect(140, 50, 41, 22))
        self.engOneJump.setMinimum(1)
        self.engOneJump.setMaximum(100)
        self.engOneJump.setObjectName("engOneJump")
        self.engTwoJump = QtWidgets.QSpinBox(self.manualGroupBox)
        self.engTwoJump.setGeometry(QtCore.QRect(140, 100, 42, 22))
        self.engTwoJump.setMinimum(1)
        self.engTwoJump.setMaximum(100)
        self.engTwoJump.setObjectName("engTwoJump")
        self.engBothJump = QtWidgets.QSpinBox(self.manualGroupBox)
        self.engBothJump.setGeometry(QtCore.QRect(140, 150, 42, 22))
        self.engBothJump.setMinimum(1)
        self.engBothJump.setMaximum(100)
        self.engBothJump.setObjectName("engBothJump")
        self.label_11 = QtWidgets.QLabel(self.manualGroupBox)
        self.label_11.setGeometry(QtCore.QRect(124, 20, 71, 20))
        self.label_11.setObjectName("label_11")
        self.engOneInit = QtWidgets.QSpinBox(self.manualGroupBox)
        self.engOneInit.setGeometry(QtCore.QRect(60, 190, 42, 22))
        self.engOneInit.setMaximum(100)
        self.engOneInit.setObjectName("engOneInit")
        self.label_12 = QtWidgets.QLabel(self.manualGroupBox)
        self.label_12.setGeometry(QtCore.QRect(10, 170, 131, 16))
        self.label_12.setObjectName("label_12")
        self.label_22 = QtWidgets.QLabel(self.manualGroupBox)
        self.label_22.setGeometry(QtCore.QRect(10, 190, 51, 16))
        self.label_22.setObjectName("label_22")
        self.label_23 = QtWidgets.QLabel(self.manualGroupBox)
        self.label_23.setGeometry(QtCore.QRect(10, 220, 55, 16))
        self.label_23.setObjectName("label_23")
        self.engTwoInit = QtWidgets.QSpinBox(self.manualGroupBox)
        self.engTwoInit.setGeometry(QtCore.QRect(60, 220, 42, 22))
        self.engTwoInit.setMaximum(100)
        self.engTwoInit.setObjectName("engTwoInit")
        self.actionManual = QtWidgets.QPushButton(self.manualGroupBox)
        self.actionManual.setGeometry(QtCore.QRect(130, 200, 61, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.actionManual.setFont(font)
        self.actionManual.setObjectName("actionManual")
        self.verticalLayout_5.addWidget(self.manualGroupBox)
        self.horizontalLayout_2.addLayout(self.verticalLayout_5)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        spacerItem1 = QtWidgets.QSpacerItem(40, 0, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout_2.addItem(spacerItem1)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.saveToFile = QtWidgets.QCheckBox(self.centralwidget)
        self.saveToFile.setChecked(True)
        self.saveToFile.setObjectName("saveToFile")
        self.verticalLayout_4.addWidget(self.saveToFile)
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setMinimumSize(QtCore.QSize(150, 180))
        self.groupBox.setMaximumSize(QtCore.QSize(150, 180))
        self.groupBox.setObjectName("groupBox")
        self.saveSpeed = QtWidgets.QCheckBox(self.groupBox)
        self.saveSpeed.setGeometry(QtCore.QRect(10, 20, 141, 20))
        self.saveSpeed.setChecked(True)
        self.saveSpeed.setObjectName("saveSpeed")
        self.saveVoltage = QtWidgets.QCheckBox(self.groupBox)
        self.saveVoltage.setGeometry(QtCore.QRect(10, 40, 81, 20))
        self.saveVoltage.setChecked(True)
        self.saveVoltage.setObjectName("saveVoltage")
        self.saveCurrent = QtWidgets.QCheckBox(self.groupBox)
        self.saveCurrent.setGeometry(QtCore.QRect(10, 60, 81, 20))
        self.saveCurrent.setChecked(True)
        self.saveCurrent.setObjectName("saveCurrent")
        self.savePressure = QtWidgets.QCheckBox(self.groupBox)
        self.savePressure.setGeometry(QtCore.QRect(10, 80, 81, 20))
        self.savePressure.setChecked(True)
        self.savePressure.setObjectName("savePressure")
        self.label_8 = QtWidgets.QLabel(self.groupBox)
        self.label_8.setGeometry(QtCore.QRect(10, 110, 81, 16))
        self.label_8.setObjectName("label_8")
        self.fileName = QtWidgets.QLineEdit(self.groupBox)
        self.fileName.setGeometry(QtCore.QRect(10, 130, 131, 22))
        self.fileName.setObjectName("fileName")
        self.verticalLayout_4.addWidget(self.groupBox)
        spacerItem2 = QtWidgets.QSpacerItem(20, 30, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem2)
        self.horizontalLayout.addLayout(self.verticalLayout_4)
        self.verticalLayout_6.addLayout(self.horizontalLayout)
        spacerItem3 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_6.addItem(spacerItem3)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.stopButton = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stopButton.sizePolicy().hasHeightForWidth())
        self.stopButton.setSizePolicy(sizePolicy)
        self.stopButton.setMinimumSize(QtCore.QSize(150, 50))
        self.stopButton.setMaximumSize(QtCore.QSize(150, 50))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.stopButton.setFont(font)
        self.stopButton.setObjectName("stopButton")
        self.horizontalLayout_3.addWidget(self.stopButton)
        self.verticalLayout_6.addLayout(self.horizontalLayout_3)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1000, 26))
        self.menubar.setObjectName("menubar")
        self.menuPlik = QtWidgets.QMenu(self.menubar)
        self.menuPlik.setObjectName("menuPlik")
        self.menuPomoc = QtWidgets.QMenu(self.menubar)
        self.menuPomoc.setObjectName("menuPomoc")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.Terminal = QtWidgets.QDockWidget(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Terminal.sizePolicy().hasHeightForWidth())
        self.Terminal.setSizePolicy(sizePolicy)
        self.Terminal.setMinimumSize(QtCore.QSize(267, 231))
        self.Terminal.setMaximumSize(QtCore.QSize(1000, 231))
        self.Terminal.setFeatures(QtWidgets.QDockWidget.DockWidgetFloatable|QtWidgets.QDockWidget.DockWidgetMovable)
        self.Terminal.setAllowedAreas(QtCore.Qt.BottomDockWidgetArea|QtCore.Qt.TopDockWidgetArea)
        self.Terminal.setObjectName("Terminal")
        self.dockWidgetContents = QtWidgets.QWidget()
        self.dockWidgetContents.setObjectName("dockWidgetContents")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.dockWidgetContents)
        self.verticalLayout.setObjectName("verticalLayout")
        self.terminal = QtWidgets.QPlainTextEdit(self.dockWidgetContents)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(240, 240, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.terminal.setPalette(palette)
        self.terminal.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.terminal.setReadOnly(True)
        self.terminal.setObjectName("terminal")
        self.verticalLayout.addWidget(self.terminal)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.horizontalLayout_4.setContentsMargins(0, 0, -1, -1)
        self.horizontalLayout_4.setSpacing(0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.quickMessage = QtWidgets.QLineEdit(self.dockWidgetContents)
        self.quickMessage.setClearButtonEnabled(False)
        self.quickMessage.setObjectName("quickMessage")
        self.horizontalLayout_4.addWidget(self.quickMessage)
        self.quickSend = QtWidgets.QPushButton(self.dockWidgetContents)
        self.quickSend.setObjectName("quickSend")
        self.horizontalLayout_4.addWidget(self.quickSend)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.Terminal.setWidget(self.dockWidgetContents)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(8), self.Terminal)
        self.actionZamknij = QtWidgets.QAction(MainWindow)
        self.actionZamknij.setObjectName("actionZamknij")
        self.actionAutorzy = QtWidgets.QAction(MainWindow)
        self.actionAutorzy.setObjectName("actionAutorzy")
        self.actionPomoc = QtWidgets.QAction(MainWindow)
        self.actionPomoc.setObjectName("actionPomoc")
        self.menuPlik.addAction(self.actionZamknij)
        self.menuPomoc.addAction(self.actionPomoc)
        self.menuPomoc.addAction(self.actionAutorzy)
        self.menubar.addAction(self.menuPlik.menuAction())
        self.menubar.addAction(self.menuPomoc.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        self.uartBaudRateList.setCurrentIndex(11)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "DynoSoft"))
        self.label.setText(_translate("MainWindow", "Wybrany sposób komunikacji:"))
        self.label_2.setText(_translate("MainWindow", "Port:"))
        self.label_3.setText(_translate("MainWindow", "BaudRate:"))
        self.uartBaudRateList.setCurrentText(_translate("MainWindow", "115200"))
        self.uartBaudRateList.setItemText(0, _translate("MainWindow", "600"))
        self.uartBaudRateList.setItemText(1, _translate("MainWindow", "1200"))
        self.uartBaudRateList.setItemText(2, _translate("MainWindow", "2400"))
        self.uartBaudRateList.setItemText(3, _translate("MainWindow", "4800"))
        self.uartBaudRateList.setItemText(4, _translate("MainWindow", "9600"))
        self.uartBaudRateList.setItemText(5, _translate("MainWindow", "14400"))
        self.uartBaudRateList.setItemText(6, _translate("MainWindow", "19200"))
        self.uartBaudRateList.setItemText(7, _translate("MainWindow", "28800"))
        self.uartBaudRateList.setItemText(8, _translate("MainWindow", "38400"))
        self.uartBaudRateList.setItemText(9, _translate("MainWindow", "56000"))
        self.uartBaudRateList.setItemText(10, _translate("MainWindow", "57600"))
        self.uartBaudRateList.setItemText(11, _translate("MainWindow", "115200"))
        self.uartBaudRateList.setItemText(12, _translate("MainWindow", "128000"))
        self.uartBaudRateList.setItemText(13, _translate("MainWindow", "256000"))
        self.rescanButton.setText(_translate("MainWindow", "Skanuj"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.uart), _translate("MainWindow", "UART"))
        self.label_4.setText(_translate("MainWindow", "VendroID:"))
        self.label_5.setText(_translate("MainWindow", "ProductID:"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.usb_hid), _translate("MainWindow", "USB HID"))
        self.connectButton.setText(_translate("MainWindow", "Połącz"))
        self.groupBox_4.setTitle(_translate("MainWindow", "Wskazania:"))
        self.label_14.setText(_translate("MainWindow", "n1 [obr/min]:"))
        self.speedMeterN1.setText(_translate("MainWindow", "0"))
        self.label_15.setText(_translate("MainWindow", "U [V]:"))
        self.voltageMeter.setText(_translate("MainWindow", "0"))
        self.label_16.setText(_translate("MainWindow", "I1 [A]:"))
        self.currentMeterI1.setText(_translate("MainWindow", "0"))
        self.label_17.setText(_translate("MainWindow", "Ciąg [g]:"))
        self.pressureMeter.setText(_translate("MainWindow", "0"))
        self.label_18.setText(_translate("MainWindow", "I2 [A]:"))
        self.currentMeterI2.setText(_translate("MainWindow", "0"))
        self.label_19.setText(_translate("MainWindow", "n2 [obr/min]:"))
        self.speedMeterN2.setText(_translate("MainWindow", "0"))
        self.label_20.setText(_translate("MainWindow", "PWM 1 [%]:"))
        self.PWMFirstMeter.setText(_translate("MainWindow", "0"))
        self.label_24.setText(_translate("MainWindow", "PWM 2 [%]:"))
        self.PWMSecondMeter.setText(_translate("MainWindow", "0"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Parametry hamowni:"))
        self.label_6.setText(_translate("MainWindow", "Liczba par biegunów silnika pierwszego:"))
        self.calibrateTens.setText(_translate("MainWindow", "Kalibracja"))
        self.label_13.setText(_translate("MainWindow", "Tensometr:"))
        self.label_21.setText(_translate("MainWindow", "Liczba par biegunów silnika drugiego (opcjonalnie):"))
        self.manualTime.setText(_translate("MainWindow", "Zabezpieczenie czasowe[s]:"))
        self.manualWork.setText(_translate("MainWindow", "Praca manualna"))
        self.manualGroupBox.setTitle(_translate("MainWindow", "Sterowanie manualne"))
        self.label_7.setText(_translate("MainWindow", "Silnik pierwszy:"))
        self.engOneMin.setText(_translate("MainWindow", "-"))
        self.engOnePlus.setText(_translate("MainWindow", "+"))
        self.engTwoPlus.setText(_translate("MainWindow", "+"))
        self.engTwoMin.setText(_translate("MainWindow", "-"))
        self.label_9.setText(_translate("MainWindow", "Silnik drugi:"))
        self.engBothPlus.setText(_translate("MainWindow", "+"))
        self.engBothMin.setText(_translate("MainWindow", "-"))
        self.label_10.setText(_translate("MainWindow", "Oba silniki:"))
        self.label_11.setText(_translate("MainWindow", "Skok [%]:"))
        self.label_12.setText(_translate("MainWindow", "Wartość początkowa:"))
        self.label_22.setText(_translate("MainWindow", "S1 [%]:"))
        self.label_23.setText(_translate("MainWindow", "S2 [%]:"))
        self.actionManual.setText(_translate("MainWindow", "START"))
        self.saveToFile.setText(_translate("MainWindow", "Zapisuj do pliku"))
        self.groupBox.setTitle(_translate("MainWindow", "Opcje zapisu"))
        self.saveSpeed.setText(_translate("MainWindow", "Prędkość obrotowa"))
        self.saveVoltage.setText(_translate("MainWindow", "Napięcie"))
        self.saveCurrent.setText(_translate("MainWindow", "Prąd"))
        self.savePressure.setText(_translate("MainWindow", "Ciąg"))
        self.label_8.setText(_translate("MainWindow", "Nazwa pliku:"))
        self.stopButton.setText(_translate("MainWindow", "STOP"))
        self.menuPlik.setTitle(_translate("MainWindow", "Plik"))
        self.menuPomoc.setTitle(_translate("MainWindow", "Pomoc"))
        self.Terminal.setWindowTitle(_translate("MainWindow", "Terminal"))
        self.quickSend.setText(_translate("MainWindow", "Wyślij"))
        self.actionZamknij.setText(_translate("MainWindow", "Zamknij"))
        self.actionAutorzy.setText(_translate("MainWindow", "Autorzy"))
        self.actionPomoc.setText(_translate("MainWindow", "Pomoc"))

