# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.5
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets
from datetime import datetime

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1000, 800)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(1000, 800))
        MainWindow.setMaximumSize(QtCore.QSize(1000, 800))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("Zrzuty/PP_logo_jasne.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setObjectName("label")
        self.verticalLayout_3.addWidget(self.label)
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        self.tabWidget.setMinimumSize(QtCore.QSize(150, 180))
        self.tabWidget.setMaximumSize(QtCore.QSize(150, 180))
        self.tabWidget.setObjectName("tabWidget")
        self.uart = QtWidgets.QWidget()
        self.uart.setObjectName("uart")
        self.label_2 = QtWidgets.QLabel(self.uart)
        self.label_2.setGeometry(QtCore.QRect(10, 10, 55, 16))
        self.label_2.setObjectName("label_2")
        self.uartPortList = QtWidgets.QComboBox(self.uart)
        self.uartPortList.setGeometry(QtCore.QRect(10, 30, 111, 22))
        self.uartPortList.setObjectName("uartPortList")
        self.label_3 = QtWidgets.QLabel(self.uart)
        self.label_3.setGeometry(QtCore.QRect(10, 90, 71, 16))
        self.label_3.setObjectName("label_3")
        self.uartBaudRateList = QtWidgets.QComboBox(self.uart)
        self.uartBaudRateList.setGeometry(QtCore.QRect(10, 110, 111, 22))
        self.uartBaudRateList.setObjectName("uartBaudRateList")
        self.uartBaudRateList.addItem("")
        self.uartBaudRateList.addItem("")
        self.uartBaudRateList.addItem("")
        self.uartBaudRateList.addItem("")
        self.uartBaudRateList.addItem("")
        self.uartBaudRateList.addItem("")
        self.uartBaudRateList.addItem("")
        self.uartBaudRateList.addItem("")
        self.uartBaudRateList.addItem("")
        self.uartBaudRateList.addItem("")
        self.uartBaudRateList.addItem("")
        self.uartBaudRateList.addItem("")
        self.uartBaudRateList.addItem("")
        self.uartBaudRateList.addItem("")
        self.tabWidget.addTab(self.uart, "")
        self.usb_hid = QtWidgets.QWidget()
        self.usb_hid.setObjectName("usb_hid")
        self.label_4 = QtWidgets.QLabel(self.usb_hid)
        self.label_4.setGeometry(QtCore.QRect(10, 10, 71, 16))
        self.label_4.setObjectName("label_4")
        self.vendorID = QtWidgets.QLineEdit(self.usb_hid)
        self.vendorID.setGeometry(QtCore.QRect(10, 30, 113, 22))
        self.vendorID.setObjectName("vendorID")
        self.label_5 = QtWidgets.QLabel(self.usb_hid)
        self.label_5.setGeometry(QtCore.QRect(10, 90, 71, 16))
        self.label_5.setObjectName("label_5")
        self.ProductID = QtWidgets.QLineEdit(self.usb_hid)
        self.ProductID.setGeometry(QtCore.QRect(10, 110, 113, 22))
        self.ProductID.setObjectName("ProductID")
        self.tabWidget.addTab(self.usb_hid, "")
        self.verticalLayout_3.addWidget(self.tabWidget)
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton.sizePolicy().hasHeightForWidth())
        self.pushButton.setSizePolicy(sizePolicy)
        self.pushButton.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout_3.addWidget(self.pushButton)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem)
        self.horizontalLayout.addLayout(self.verticalLayout_3)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.saveToFile = QtWidgets.QCheckBox(self.centralwidget)
        self.saveToFile.setChecked(True)
        self.saveToFile.setObjectName("saveToFile")
        self.verticalLayout_4.addWidget(self.saveToFile)
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setMinimumSize(QtCore.QSize(150, 180))
        self.groupBox.setMaximumSize(QtCore.QSize(150, 180))
        self.groupBox.setObjectName("groupBox")
        self.saveSpeed = QtWidgets.QCheckBox(self.groupBox)
        self.saveSpeed.setGeometry(QtCore.QRect(10, 30, 141, 20))
        self.saveSpeed.setChecked(True)
        self.saveSpeed.setObjectName("saveSpeed")
        self.saveVoltage = QtWidgets.QCheckBox(self.groupBox)
        self.saveVoltage.setGeometry(QtCore.QRect(10, 60, 81, 20))
        self.saveVoltage.setChecked(True)
        self.saveVoltage.setObjectName("saveVoltage")
        self.saveCurrent = QtWidgets.QCheckBox(self.groupBox)
        self.saveCurrent.setGeometry(QtCore.QRect(10, 90, 81, 20))
        self.saveCurrent.setChecked(True)
        self.saveCurrent.setObjectName("saveCurrent")
        self.savePressure = QtWidgets.QCheckBox(self.groupBox)
        self.savePressure.setGeometry(QtCore.QRect(10, 120, 81, 20))
        self.savePressure.setChecked(True)
        self.savePressure.setObjectName("savePressure")
        self.saveSpeed.raise_()
        self.saveVoltage.raise_()
        self.saveCurrent.raise_()
        self.savePressure.raise_()
        self.saveToFile.raise_()
        self.verticalLayout_4.addWidget(self.groupBox)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem2)
        self.horizontalLayout.addLayout(self.verticalLayout_4)
        self.verticalLayout_6.addLayout(self.horizontalLayout)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_6.addItem(spacerItem3)
        self.stopButton = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stopButton.sizePolicy().hasHeightForWidth())
        self.stopButton.setSizePolicy(sizePolicy)
        self.stopButton.setMinimumSize(QtCore.QSize(150, 50))
        self.stopButton.setMaximumSize(QtCore.QSize(150, 50))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.stopButton.setFont(font)
        self.stopButton.setObjectName("stopButton")
        self.verticalLayout_6.addWidget(self.stopButton)
        self.groupBox.raise_()
        self.stopButton.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1000, 26))
        self.menubar.setObjectName("menubar")
        self.menuPlik = QtWidgets.QMenu(self.menubar)
        self.menuPlik.setObjectName("menuPlik")
        self.menuWidok = QtWidgets.QMenu(self.menubar)
        self.menuWidok.setObjectName("menuWidok")
        self.menuPomoc = QtWidgets.QMenu(self.menubar)
        self.menuPomoc.setObjectName("menuPomoc")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.Terminal = QtWidgets.QDockWidget(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Terminal.sizePolicy().hasHeightForWidth())
        self.Terminal.setSizePolicy(sizePolicy)
        self.Terminal.setMinimumSize(QtCore.QSize(109, 200))
        self.Terminal.setMaximumSize(QtCore.QSize(1000, 400))
        self.Terminal.setObjectName("Terminal")
        self.dockWidgetContents = QtWidgets.QWidget()
        self.dockWidgetContents.setObjectName("dockWidgetContents")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.dockWidgetContents)
        self.verticalLayout.setObjectName("verticalLayout")
        self.terminal = QtWidgets.QPlainTextEdit(self.dockWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.terminal.sizePolicy().hasHeightForWidth())
        self.terminal.setSizePolicy(sizePolicy)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.terminal.setPalette(palette)
        self.terminal.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.terminal.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.terminal.setReadOnly(True)
        self.terminal.setObjectName("terminal")
        self.verticalLayout.addWidget(self.terminal)
        self.Terminal.setWidget(self.dockWidgetContents)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(8), self.Terminal)
        self.menubar.addAction(self.menuPlik.menuAction())
        self.menubar.addAction(self.menuWidok.menuAction())
        self.menubar.addAction(self.menuPomoc.menuAction())

        self.saveToFile.stateChanged.connect(self.saveToFileStateChanged)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        self.uartBaudRateList.setCurrentIndex(4)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "DynoSoft"))
        self.label.setText(_translate("MainWindow", "Wybrany sposób komunikacji:"))
        self.label_2.setText(_translate("MainWindow", "Port:"))
        self.label_3.setText(_translate("MainWindow", "BaudRate:"))
        self.uartBaudRateList.setItemText(0, _translate("MainWindow", "600"))
        self.uartBaudRateList.setItemText(1, _translate("MainWindow", "1200"))
        self.uartBaudRateList.setItemText(2, _translate("MainWindow", "2400"))
        self.uartBaudRateList.setItemText(3, _translate("MainWindow", "4800"))
        self.uartBaudRateList.setItemText(4, _translate("MainWindow", "9600"))
        self.uartBaudRateList.setItemText(5, _translate("MainWindow", "14400"))
        self.uartBaudRateList.setItemText(6, _translate("MainWindow", "19200"))
        self.uartBaudRateList.setItemText(7, _translate("MainWindow", "28800"))
        self.uartBaudRateList.setItemText(8, _translate("MainWindow", "38400"))
        self.uartBaudRateList.setItemText(9, _translate("MainWindow", "56000"))
        self.uartBaudRateList.setItemText(10, _translate("MainWindow", "57600"))
        self.uartBaudRateList.setItemText(11, _translate("MainWindow", "115200"))
        self.uartBaudRateList.setItemText(12, _translate("MainWindow", "128000"))
        self.uartBaudRateList.setItemText(13, _translate("MainWindow", "256000"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.uart), _translate("MainWindow", "UART"))
        self.label_4.setText(_translate("MainWindow", "VendroID:"))
        self.label_5.setText(_translate("MainWindow", "ProductID:"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.usb_hid), _translate("MainWindow", "USB HID"))
        self.pushButton.setText(_translate("MainWindow", "Połącz"))
        self.saveToFile.setText(_translate("MainWindow", "Zapisuj do pliku"))
        self.groupBox.setTitle(_translate("MainWindow", "Opcje zapisu"))
        self.saveSpeed.setText(_translate("MainWindow", "Prędkość obrotowa"))
        self.saveVoltage.setText(_translate("MainWindow", "Napięcie"))
        self.saveCurrent.setText(_translate("MainWindow", "Prąd"))
        self.savePressure.setText(_translate("MainWindow", "Nacisk"))
        self.stopButton.setText(_translate("MainWindow", "STOP"))
        self.menuPlik.setTitle(_translate("MainWindow", "Plik"))
        self.menuWidok.setTitle(_translate("MainWindow", "Widok"))
        self.menuPomoc.setTitle(_translate("MainWindow", "Pomoc"))
        self.Terminal.setWindowTitle(_translate("MainWindow", "Terminal"))

    def saveToFileStateChanged(self, state):
        if state == 0:
            self.groupBox.setEnabled(False)

            self.terminal.appendPlainText(datetime.now().strftime("%H:%M:%S.%f") + ': Zapisywanie plikow wylaczone')

        else:
            self.groupBox.setEnabled(True)
            self.terminal.appendPlainText(datetime.now().strftime("%H:%M:%S.%f") + ': Zapisywanie plikow wlaczone')


